### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/project-promo-i-module-1-team-2-morning#1]
Hola, os paso unas mejorillas:

A destacar:

- Según la RAE limpieza significa esto: https://github.com/Adalab/project-promo-i-module-1-team-2-morning/blob/master/_src/templates/index.html
- Este alt también es bien: https://github.com/Adalab/project-promo-i-module-1-team-2-morning/blob/master/_src/templates/partials/_about-us-adalabers.html#L13
- El HTML en general está perfecto
- Habéis limpiado las carpetas que no usais: https://github.com/Adalab/project-promo-i-module-1-team-2-morning/tree/master/_src/assets
- Muchas variables es bien https://github.com/Adalab/project-promo-i-module-1-team-2-morning/blob/master/_src/assets/scss/core/_variables.scss

A mejorar:

- [x] Yo le pondría type=email https://github.com/Adalab/project-promo-i-module-1-team-2-morning/blob/master/_src/templates/contact.html#L38
- [x] No usemos etiquetas como selectores https://github.com/Adalab/project-promo-i-module-1-team-2-morning/blob/master/_src/assets/scss/components/_footer.scss#L58

Me gusta mucho cómo habéis trabajado y el resultado obtenido!!!

![https://media.giphy.com/media/dYmAGbrm5Iv4HTOVwm/giphy.gif](https://media.giphy.com/media/dYmAGbrm5Iv4HTOVwm/giphy.gif)

**Comment by griselmatosm** [comment]
Muchas gracias Miguel!!! Hemos trabajado muy a gusto como equipo la verdad!
